### ISSUE TITLE
range determination via xparse?

### ISSUE THREAD

**Issue by FrankMittelbach** [patta42/lipsum#3]
xparse has good facilities to split an argument and pass on the result as separate `#1 #2 ...` so that `1` becomes `{1}{1} `and `1-3` becomes `{1}{3}` for further processing.

**Comment by patta42** [comment]
I have (briefly) looked into this. But I have one problem:

```
\documentclass{article}

\usepackage{xparse}
\ExplSyntaxOn
\tl_new:N\mydefault_tl
\tl_gset:Nn\mydefault_tl{1-7}
\cs_new:Npn \set_start_end:nn #1#2 {
  (#1)--(#2)
  \int_set:Nn\l_tmpa_int{#1}
  \IfNoValueTF{#2}
  {
    \int_set:Nn\l_tmpb_int{#1}
  }
  {
    \int_set:Nn\l_tmpb_int{#2}
  }
}
\NewDocumentCommand\test{>{\SplitArgument{1}{-}}O{\tl_use:N\mydefault_tl}}{
    \set_start_end:nn #1
    1:~\int_use:N\l_tmpa_int ~|~ 
    2:~\int_use:N\l_tmpb_int
}
  \ExplSyntaxOff
\begin{document}
\test[1]

\test[1-2]

\test

\end{document}
```

In case of the default value, `\SplitArgument` has to operate on the expanded argument, but it does not. Thus, {1-7} is parsed as integer and the result is -6.

Have I missed anything which allows to defines a `\NewDocumentCommand` which expands its arguments? Also, it seems that I cannot use `\exp_args:Ne` since this requires a function as first argument, expands the second argument, and puts both back to the input stream. Hence, something like `>{\exp_args:Ne\SplitArgument #1 {1}{-}` will not have the correct order of arguments.

**Comment by FrankMittelbach** [comment]
Am 03.11.18 um 16:51 schrieb patta42:
> Have I missed anything which allows to defines a |\NewDocumentCommand| 
> which expands its arguments?

don't think you have, that use case is missing I guess.

Try this:

\cs_generate_variant:Nn \__xparse_split_argument:nnn {nne}
\cs_new_eq:NN \SplitArgumentExpanded \__xparse_split_argument:nne


\NewDocumentCommand\test{>{\SplitArgument{1}{-}}O{\tl_use:N\mydefault_tl}}{

I guess we should have something like this

frank

**Comment by patta42** [comment]
>  \NewDocumentCommand\test{>{\SplitArgument{1}{-}}O{\tl_use:N\mydefault_tl}}{
> I guess we should have something like this

Does this mean it will make its way in xparse? I have implemented this as a local command to avoid naming conflicts in case xparse will provide it one day.

**Comment by patta42** [comment]
c2e745d2a555b31f47fc91b8de3474384d893f94
